name: Build

on:
  push:
    branches: master

jobs:
  build:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
        
      - name: Install Expo and EAS
        run: npm install expo expo-cli eas-cli

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: latest
          eas-version: latest
          username: ${{ secrets.EXPO_CLI_USERNAME }}
          password: ${{ secrets.EXPO_CLI_PASSWORD }}
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install
        
      - name: Build Android APK Bundle
        run: eas build --platform android
